group:
  - arcee

task: patents_gen_abstract

dataset_path: parquet
dataset_name: null
dataset_kwargs:
  data_files:
    #test: s3://shamane-siri-output/pubmed_only.parquet/part-00000-786fa4aa-d990-455d-8143-eab9ef9a48e1-c000.snappy.parquet
    #test: /home/ubuntu/src/data_pmc_test/part-00299-786fa4aa-d990-455d-8143-eab9ef9a48e1-c000.snappy.parquet
    test: /home/ubuntu/src/data/new_patents_abstract_gen.parquet

output_type: loglikelihood_rolling
training_split: null
validation_split: null
test_split: test
fewshot_split: null

doc_to_text: !function patents.doc_to_text
doc_to_target: !function patents.doc_to_target

metadata:
  version: 2.0
