group:
  - arcee

task: pubmed500

dataset_path: csv
dataset_name: null
dataset_kwargs:
  data_files:
    test: s3://arcee-public/pubmed500.csv

output_type: loglikelihood_rolling
training_split: null
validation_split: null
test_split: test
fewshot_split: test

process_docs: !function preprocess_pubmed.process_docs
doc_to_text: ""
doc_to_target: !function preprocess_pubmed.doc_to_text_pubmed500


#metric_list:
#  - metric: word_perplexity
#  - metric: byte_perplexity
#  - metric: bits_per_byte

metadata:
  version: 2.0
